### ISSUE TITLE
In mobileview - Show productimage if productimage and merchantlogo are selected in template options.

### ISSUE THREAD

**Issue by shayansalehi** [NoorDigitalAgency/datafeedr-comparison-template#3]
https://europe-enterprise.taskworld.com/noor/#/project/665?show=/task/51184

![image](https://user-images.githubusercontent.com/26716958/104890660-28c2db00-5970-11eb-8dc0-33d729473ac4.png)

**Comment by Chrillaz** [comment]
Implemented in v1.2.0
